[package]
name = "snd_client_rs"
version = "0.1.0"
edition = "2021"
authors = ["eric Sk3pz <skepz.dev@gmail.com>"]
description = "The official SnD client written in rust"
repository = "https://github.com/Sk3pz/SwordsAndDeath"
license = "MIT"

[dependencies]
